server:
  port: 8086

spring:
  application:
    name: fraud
  datasource:
    password: '17747274'
    url: jdbc:postgresql://localhost:5432/fraud?currentSchema=public
    username: 'root'
  jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
      hibernate:
        ddl-auto: create-drop
      show-sql: 'true'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka